theme = "gruvbox_material_dark_hard"

[editor]
bufferline = "multiple"
end-of-line-diagnostics = "hint"
cursorline = true

[editor.lsp]
display-inlay-hints = true
display-progress-messages = true

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
A-up = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-down = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
C-l = ":open ~/.config/helix/languages.toml"
H = ":buffer-previous"
L = ":buffer-next"

[keys.normal.space]
t = ':sh exec kitty'
q = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ':set mouse false',
  ':set mouse true',
]

