# Language Servers

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config.preview.browsing]
args = ["--data-plane-host=127.0.0.1:0", "--invert-colors=never", "--open"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config]
tsserver = { path = "/usr/lib/node_modules/typescript/lib/" } # Ensure usage of global tsc version.
preferences = { includeInlayVariableTypeHints = true }

# Languages

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "typst"
language-servers = ["tinymist", "harper-ls"]
formatter = { command = "typstyle" }

[[language]]
name = "rust"
auto-format = true
